# Generated by Django 3.2.7 on 2022-11-29 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lodge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('homeImg', models.ImageField(blank=True, default='Profile-Photo-Place-Holder.PNG', null=True, upload_to='home_img')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('ref', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='0.jpg', upload_to='profile_pics')),
                ('email', models.EmailField(default='egwusamuel2015@gmail.com', max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LodgeProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorrounding', models.ImageField(blank=True, null=True, upload_to='home_img')),
                ('lodge_interior', models.ImageField(blank=True, null=True, upload_to='home_img')),
                ('roomFront', models.ImageField(blank=True, null=True, upload_to='home_img')),
                ('roomBack', models.ImageField(blank=True, null=True, upload_to='home_img')),
                ('roomKitchen', models.ImageField(blank=True, null=True, upload_to='home_img')),
                ('roomToiletBath', models.ImageField(blank=True, null=True, upload_to='home_img')),
                ('bedRoom', models.ImageField(blank=True, null=True, upload_to='home_img')),
                ('roomsTotalNum', models.PositiveSmallIntegerField()),
                ('roomsAvailable', models.PositiveSmallIntegerField()),
                ('selfCon', models.BooleanField(default=False)),
                ('lodge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OffKLodges.lodge')),
            ],
        ),
    ]
