# Generated by Django 3.2.7 on 2022-12-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffKLodges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Profile-Photo-Place-Holder.jpg', upload_to='profile_pics'),
        ),
    ]
