# Generated by Django 3.2.7 on 2023-01-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffKLodges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='distance',
            field=models.CharField(default='200 meters from school', max_length=200),
        ),
        migrations.AddField(
            model_name='lodge',
            name='elec_water',
            field=models.CharField(default='Stable Electricity and Water', max_length=200),
        ),
        migrations.AddField(
            model_name='lodge',
            name='self_con',
            field=models.CharField(default='1 Bedroom Self contain', max_length=200),
        ),
    ]
