# Generated by Django 3.2.7 on 2023-01-06 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffKLodges', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindRoomMates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(choices=[('abuja', 'Abuja'), ('abia', 'Abia'), ('adamawa', 'Adamawa'), ('anambra', 'Anambra'), ('akwa Ibom', 'Akwa Ibom'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('benue', 'Benue'), ('borno', 'Borno'), ('cross River', 'cross River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('edo', 'Edo'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('gombe', 'Gombe'), ('imo', 'Imo'), ('jigawa', 'Jigawa'), ('kaduna', 'Kaduna'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kebbi', 'kebbi'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('nassarawa', 'Nassarawa'), ('niger', 'Niger'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('plateau', 'Plateau'), ('rivers', 'Rivers'), ('sokoto', 'Sokoto'), ('taraba', 'Taraba'), ('yobe', 'Yobe'), ('zamfara', 'Zamfara'), ("I don't care", "I don't care")], default="I don't care", max_length=200)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ("I don't care", "I don't care")], default="I don't care", max_length=200)),
                ('level', models.CharField(choices=[('100L', '100L'), ('200L', '200L'), ('300L', '300L'), ('400L', '400L'), ('500L', '500L'), ("I don't care", "I don't care")], default="I don't care", max_length=200)),
                ('earlywake', models.CharField(choices=[('early', 'Early'), ('late', 'Late'), ("I don't care", "I don't care")], default="I don't care", max_length=200)),
                ('noise', models.CharField(choices=[('silence', 'Silence'), ('background noise', 'Background noise'), ("I don't care", "I don't care")], default="I don't care", max_length=200)),
                ('organizedSpace', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ("I don't care", "I don't care")], default="I don't care", max_length=200)),
                ('grocries', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ("I don't care", "I don't care")], default="I don't care", max_length=200)),
                ('personalSpace', models.CharField(choices=[('spend time with my roomate', 'Spend time with my roomate'), ('have my own space and time', 'Have my own space and time'), ("I don't care", "I don't care")], default="I don't care", max_length=200)),
                ('disabilites', models.CharField(choices=[('allergies', 'Allergies'), ('disabilities', 'Disabilities'), ("I don't care", "I don't care")], default="I don't care", max_length=200)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('match_score', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Profile-Photo-Place-Holder.png', upload_to='profile_pics'),
        ),
    ]
