# Generated by Django 3.2.7 on 2023-01-24 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffKLodges', '0003_auto_20230124_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodge',
            name='self_con',
        ),
        migrations.AlterField(
            model_name='newpayment',
            name='date_created',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
