# Generated by Django 3.2.7 on 2023-01-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffKLodges', '0003_auto_20230117_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
