# Generated by Django 3.2.7 on 2023-01-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffKLodges', '0005_alter_profile_uni_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uni_level',
            field=models.CharField(choices=[('100L', '100L'), ('200L', '200L'), ('300L', '300L'), ('400L', '400L'), ('500L', '500L')], default='100L', max_length=200),
        ),
    ]
