# Generated by Django 3.2.7 on 2023-01-20 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OffKLodges', '0006_alter_profile_uni_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedLodge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('lodge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OffKLodges.lodge')),
            ],
        ),
    ]
